# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30f64902ffdd3117a9e4f0eb8078dff299c4182c79153bbc7aeeb48721d557b5df05452c94b6e7175e771195b34fafc58ba82a6740f86d70b843774a3b510586

test:
  secret_key_base: 5604595086708c4df228e55e0f78a97dc2996e9c20aedb89e9943b5ccbdea61ad4694385f281562d645541b7de779261c6422e4e82628e0cc5ff663565a0b041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
